import { ModelMeta } from '@/types'

export const MODELS: Record<string, ModelMeta> = {
  abc: {
    key: 'abc',
    name: 'Estrutura do Texto',
    shortName: 'ET',
    icon: '📖',
    desc: 'Estrutura do Texto',
    welcome: 'Digite um versículo ou perícope e receba um estudo técnico estruturado em 10 blocos fixos.',
    verse: '"Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção..."',
    verseRef: '— 2 Timóteo 3:16',
    blocks: ['Exegese', 'Teologia Sistemática', 'Autor', 'Destinatários', 'Tema Central', 'Contexto Histórico', 'Palavras Originais', 'Gênero Literário', 'Cristocentrismo', 'Contexto Canônico'],
    plan: 'free',
  },
  eep: {
    key: 'eep',
    name: 'Exposição Contínua',
    shortName: 'EC',
    icon: '📚',
    desc: 'Exposição Contínua',
    welcome: 'Envie uma perícope ou seção inteira e receba um estudo verso a verso pronto para ser ensinado.',
    verse: '"Sede, porém, praticantes da Palavra, e não somente ouvintes."',
    verseRef: '— Tiago 1:22',
    blocks: ['Contexto', 'Estrutura', 'Verso a Verso', 'Teologia', 'Aplicação', 'Homilética'],
    plan: 'pro',
  },
  emi: {
    key: 'emi',
    name: 'Intenção do Autor',
    shortName: 'IA',
    icon: '🧠',
    desc: 'Intenção do Autor',
    welcome: 'Digite um texto com carga emocional e vamos entrar na mente, urgência e emoção do escritor bíblico.',
    verse: '"Homens santos falaram da parte de Deus, movidos pelo Espírito Santo."',
    verseRef: '— 2 Pedro 1:21',
    blocks: ['Emoção do Autor', 'Intenção', 'Urgência', 'Contexto Pessoal', 'Impacto', 'Aplicação'],
    plan: 'pro',
  },
  evr: {
    key: 'evr',
    name: 'Verso Aplicado',
    shortName: 'VA',
    icon: '🔥',
    desc: 'Verso Aplicado',
    welcome: 'Digite um versículo e receba o devocional no formato CENA → VERSO → VERDADE → REALIDADE → RESPOSTA.',
    verse: '"A Palavra de Deus é viva e eficaz, mais cortante do que qualquer espada de dois gumes..."',
    verseRef: '— Hebreus 4:12',
    blocks: ['Cena', 'Verso', 'Verdade', 'Realidade', 'Resposta'],
    plan: 'pro',
  },
  cli: {
    key: 'cli',
    name: 'Contexto do Livro',
    shortName: 'CL',
    icon: '🗺️',
    desc: 'Contexto do Livro',
    welcome: 'Digite o nome de um livro bíblico e receba o mapa panorâmico completo em 13 blocos.',
    verse: '"A exposição das tuas palavras ilumina e dá entendimento aos simples."',
    verseRef: '— Salmo 119:130',
    blocks: ['Autor', 'Destinatários', 'Data', 'Contexto Histórico', 'Problema Central', 'Erros Combatidos', 'Mensagem', 'Temas', 'Palavras-chave', 'Estrutura', 'Versículos-chave', 'Alertas', 'Aplicação'],
    plan: 'pro',
  },
}

export const MODEL_LIST = Object.values(MODELS)
