import { ModelMeta } from '@/types'

export const MODELS: Record<string, ModelMeta> = {
  abc: {
    key: 'abc',
    name: 'Análise Completa',
    shortName: 'AC',
    icon: '📖',
    desc: 'Análise Completa',
    welcome: 'Realiza uma análise bíblica profunda e organizada, abordando exegese, teologia sistemática, autoria, destinatários, contexto histórico, palavras no original, gênero literário, cristocentrismo e contexto canônico. Ideal para estudo acadêmico e fundamentação sólida do texto.',
    verse: '"Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção..."',
    verseRef: '— 2 Timóteo 3:16',
    blocks: ['Exegese', 'Teologia Sistemática', 'Autor', 'Destinatários', 'Tema Central', 'Contexto Histórico', 'Palavras Originais', 'Gênero Literário', 'Cristocentrismo', 'Contexto Canônico'],
    plan: 'free',
  },
  eep: {
    key: 'eep',
    name: 'Exposição Verso a Verso',
    shortName: 'EV',
    icon: '📚',
    desc: 'Exposição Verso a Verso',
    welcome: 'Percorre o texto de forma contínua, explicando cada verso dentro do fluxo narrativo ou argumentativo. Integra interpretação e aplicação prática, mantendo a coerência interna da perícope. Indicado para capítulos e trechos extensos.',
    verse: '"Sede, porém, praticantes da Palavra, e não somente ouvintes."',
    verseRef: '— Tiago 1:22',
    blocks: ['Contexto', 'Estrutura', 'Verso a Verso', 'Teologia', 'Aplicação', 'Homilética'],
    plan: 'pro',
  },
  emi: {
    key: 'emi',
    name: 'Intenção do Autor',
    shortName: 'IA',
    icon: '🧠',
    desc: 'Intenção do Autor',
    welcome: 'Explora o contexto emocional, espiritual e ministerial do autor, identificando urgência, propósito e carga afetiva do texto. Analisa como o autor desejava ser compreendido e como sua experiência influencia a mensagem.',
    verse: '"Homens santos falaram da parte de Deus, movidos pelo Espírito Santo."',
    verseRef: '— 2 Pedro 1:21',
    blocks: ['Emoção do Autor', 'Intenção', 'Urgência', 'Contexto Pessoal', 'Impacto', 'Aplicação'],
    plan: 'pro',
  },
  evr: {
    key: 'evr',
    name: 'Aplicação do Verso',
    shortName: 'AV',
    icon: '🔥',
    desc: 'Aplicação do Verso',
    welcome: 'Extrai a verdade central do texto e a transforma em confronto e ação prática imediata. Modelo objetivo e devocional, ideal para uso diário e reflexão pessoal estruturada.',
    verse: '"A Palavra de Deus é viva e eficaz, mais cortante do que qualquer espada de dois gumes..."',
    verseRef: '— Hebreus 4:12',
    blocks: ['Cena', 'Verso', 'Verdade', 'Realidade', 'Resposta'],
    plan: 'pro',
  },
  cli: {
    key: 'cli',
    name: 'Contexto do Livro',
    shortName: 'CL',
    icon: '🗺️',
    desc: 'Contexto do Livro',
    welcome: 'Apresenta visão macro do livro bíblico, incluindo autoria, destinatários, data, cenário histórico, problema central, temas recorrentes, estrutura literária e alertas de interpretação. Serve como base estratégica antes da análise detalhada.',
    verse: '"A exposição das tuas palavras ilumina e dá entendimento aos simples."',
    verseRef: '— Salmo 119:130',
    blocks: ['Autor', 'Destinatários', 'Data', 'Contexto Histórico', 'Problema Central', 'Erros Combatidos', 'Mensagem', 'Temas', 'Palavras-chave', 'Estrutura', 'Versículos-chave', 'Alertas', 'Aplicação'],
    plan: 'pro',
  },
}

export const MODEL_LIST = Object.values(MODELS)
